# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sslknife < Formula
  desc "Swiss-army knife for TLS, certificates, PKI and SSH keys"
  homepage "https://github.com/matusso/sslknife"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matusso/sslknife/releases/download/v0.3.0/sslknife_0.3.0_darwin_amd64.tar.gz"
      sha256 "443963cae67c3f887dfafd90fe4d3a60d830929bfa55574b5340c8aaf152e001"

      define_method(:install) do
        bin.install "sslknife"
        generate_completions_from_executable(bin/"sslknife", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matusso/sslknife/releases/download/v0.3.0/sslknife_0.3.0_darwin_arm64.tar.gz"
      sha256 "2cfc9e7180a707a0caef81612c39fd6c53973f7994ec0a711853855f53353959"

      define_method(:install) do
        bin.install "sslknife"
        generate_completions_from_executable(bin/"sslknife", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matusso/sslknife/releases/download/v0.3.0/sslknife_0.3.0_linux_amd64.tar.gz"
      sha256 "e373794ad1cb3c226faee9058a0955ed6f18f2f7e8934fe10781ca5028851be7"
      define_method(:install) do
        bin.install "sslknife"
        generate_completions_from_executable(bin/"sslknife", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matusso/sslknife/releases/download/v0.3.0/sslknife_0.3.0_linux_arm64.tar.gz"
      sha256 "b7a6ef0a33ca63cd17352fbc916fc978ca43ef98954d5aacdd14d7f4fea5092b"
      define_method(:install) do
        bin.install "sslknife"
        generate_completions_from_executable(bin/"sslknife", "completion")
      end
    end
  end

  test do
    system "#{bin}/sslknife", "version"
  end
end
